<a href="https://colab.research.google.com/github/TheCraw08/ConradWilson_TCS/blob/main/Conrad_Wilson.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv("chicago_traffic_crashes_clean.csv")
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40688 entries, 0 to 40687
Data columns (total 37 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   CRASH_RECORD_ID                40688 non-null  object
 1   CRASH_DATE                     40687 non-null  object
 2   POSTED_SPEED_LIMIT             40687 non-null  float64
 3   TRAFFIC_CONTROL_DEVICE         40687 non-null  object
 4   DEVICE_CONDITION               40687 non-null  object
 5   WEATHER_CONDITION              40687 non-null  object
 6   LIGHTING_CONDITION             40687 non-null  object
 7   FIRST_CRASH_TYPE               40687 non-null  object
 8   TRAFFICWAY_TYPE                40687 non-null  object
 9   ALIGNMENT                      40687 non-null  object
 10  ROADWAY_SURFACE_COND           40687 non-null  object
 11  ROAD_DEFECT                    40687 non-null  object
 12  REPORT_TYPE                    38731 non-null  object
 13  CRASH_TYPE                     40687 non-null  object
 14  INTERSECTION_RELATED_I         9310 non-null   object
 15  NOT_RIGHT_OF_WAY_I             1570 non-null   object
 16  HIT_AND_RUN_I                  12880 non-null  object
 17  DAMAGE                         40687 non-null  object
 18  PRIM_CONTRIBUTORY_CAUSE        40687 non-null  object
 19  STREET_NO                      40687 non-null  float64
 20  STREET_DIRECTION               40687 non-null  object
 21  STREET_NAME                    40687 non-null  object
 22  BEAT_OF_OCCURRENCE             40687 non-null  float64
 23  NUM_UNITS                      40687 non-null  float64
 24  CRASH_MONTH                    40687 non-null  float64
 25  MOST_SEVERE_INJURY             40612 non-null  object
 26  INJURIES_TOTAL                 40612 non-null  float64
 27  INJURIES_FATAL                 40612 non-null  float64
 28  INJURIES_INCAPACITATING        40612 non-null  float64
 29  INJURIES_NON_INCAPACITATING    40612 non-null  float64
 30  INJURIES_REPORTED_NOT_EVIDENT  40612 non-null  float64
 31  INJURIES_NO_INDICATION         40612 non-null  float64
 32  INJURIES_UNKNOWN               40612 non-null  float64
 33  CRASH_HOUR                     40687 non-null  float64
 34  CRASH_DAY_OF_WEEK              40687 non-null  float64
 35  LATITUDE                       40283 non-null  float64
 36  LONGITUDE                      40283 non-null  float64
dtypes: float64(16), object(21)
memory usage: 11.5+ MB

In [12]:
df.duplicated().sum()
df.drop_duplicates()

,CRASH_RECORD_ID,CRASH_DATE,POSTED_SPEED_LIMIT,TRAFFIC_CONTROL_DEVICE,DEVICE_CONDITION,WEATHER_CONDITION,LIGHTING_CONDITION,FIRST_CRASH_TYPE,TRAFFICWAY_TYPE,ALIGNMENT,...,INJURIES_FATAL,INJURIES_INCAPACITATING,INJURIES_NON_INCAPACITATING,INJURIES_REPORTED_NOT_EVIDENT,INJURIES_NO_INDICATION,INJURIES_UNKNOWN,CRASH_HOUR,CRASH_DAY_OF_WEEK,LATITUDE,LONGITUDE
0,97cf190f22c685eb4b230e45af541539cd5e959f826fcc...,07/01/2025 01:53:00 AM,30.0,STOP SIGN/FLASHER,FUNCTIONING PROPERLY,CLEAR,"DARKNESS, LIGHTED ROAD",REAR END,ONE-WAY,STRAIGHT AND LEVEL,...,0.0,0.0,0.0,0.0,2.0,0.0,1.0,3.0,41.774060,-87.650566
1,7c8df24cec0704cdf2a33cd3f45887f5d369eb4adcbb34...,07/01/2025 02:33:00 AM,20.0,STOP SIGN/FLASHER,FUNCTIONING PROPERLY,CLEAR,"DARKNESS, LIGHTED ROAD",ANGLE,T-INTERSECTION,STRAIGHT AND LEVEL,...,0.0,0.0,0.0,0.0,3.0,0.0,2.0,3.0,41.808073,-87.716296
2,2014d5458553f4b715b431187013ef0af33befcee1264b...,07/01/2025 03:00:00 AM,25.0,NO CONTROLS,NO CONTROLS,CLEAR,"DARKNESS, LIGHTED ROAD",PARKED MOTOR VEHICLE,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,0.0,0.0,1.0,0.0,3.0,3.0,41.740770,-87.582686
3,93ad86f07c3f92d32e6b86b8751d6ad57af91b80cc13ad...,07/01/2025 03:00:00 AM,20.0,NO CONTROLS,NO CONTROLS,CLEAR,"DARKNESS, LIGHTED ROAD",PARKED MOTOR VEHICLE,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,0.0,0.0,1.0,0.0,3.0,3.0,41.732970,-87.631716
4,f4b3dd08247130eca417c355f37431f25b088f4d1beb75...,07/01/2025 03:00:00 AM,30.0,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLEAR,"DARKNESS, LIGHTED ROAD",TURNING,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,0.0,1.0,2.0,0.0,3.0,3.0,42.011977,-87.698987
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40683,aecd841c494cc40118de9fccc446124030db85c3de8c98...,11/09/2025 02:45:00 PM,30.0,NO CONTROLS,NO CONTROLS,SNOW,DAYLIGHT,FIXED OBJECT,FOUR WAY,STRAIGHT AND LEVEL,...,0.0,0.0,0.0,0.0,1.0,0.0,14.0,1.0,41.912246,-87.674413
40684,20ead6bf209b51efa5ade7e9e87226fbd07c8b9be3a779...,11/09/2025 03:00:00 PM,30.0,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,UNKNOWN,DAYLIGHT,TURNING,NOT DIVIDED,STRAIGHT AND LEVEL,...,0.0,0.0,0.0,0.0,3.0,0.0,15.0,1.0,41.925337,-87.658602
40685,63433e41f95e30c96dc0963c05743abe265c7f9680f171...,11/09/2025 03:00:00 PM,15.0,NO CONTROLS,NO CONTROLS,CLOUDY/OVERCAST,DAYLIGHT,FIXED OBJECT,PARKING LOT,STRAIGHT AND LEVEL,...,0.0,0.0,0.0,0.0,1.0,0.0,15.0,1.0,41.868890,-87.639099
40686,89e75ac4c25f56b90e2f5e0997007931f243eea232978c...,11/09/2025 03:00:00 PM,30.0,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLEAR,DAYLIGHT,REAR END,DIVIDED - W/MEDIAN (NOT RAISED),STRAIGHT AND LEVEL,...,0.0,0.0,0.0,1.0,1.0,0.0,15.0,1.0,41.705439,-87.681445
40687,cf311e330c5276a62053710662d248c2f2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df.duplicated().sum()

np.int64(0)

In [18]:
df_sorted = df.sort_values(by="LIGHTING_CONDITION", ascending = False)
df_sorted.info()

<class 'pandas.core.frame.DataFrame'>
Index: 40688 entries, 11187 to 40687
Data columns (total 37 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   CRASH_RECORD_ID                40688 non-null  object
 1   CRASH_DATE                     40687 non-null  object
 2   POSTED_SPEED_LIMIT             40687 non-null  float64
 3   TRAFFIC_CONTROL_DEVICE         40687 non-null  object
 4   DEVICE_CONDITION               40687 non-null  object
 5   WEATHER_CONDITION              40687 non-null  object
 6   LIGHTING_CONDITION             40687 non-null  object
 7   FIRST_CRASH_TYPE               40687 non-null  object
 8   TRAFFICWAY_TYPE                40687 non-null  object
 9   ALIGNMENT                      40687 non-null  object
 10  ROADWAY_SURFACE_COND           40687 non-null  object
 11  ROAD_DEFECT                    40687 non-null  object
 12  REPORT_TYPE                    38731 non-null  object
 13  CRASH_TYPE                     40687 non-null  object
 14  INTERSECTION_RELATED_I         9310 non-null   object
 15  NOT_RIGHT_OF_WAY_I             1570 non-null   object
 16  HIT_AND_RUN_I                  12880 non-null  object
 17  DAMAGE                         40687 non-null  object
 18  PRIM_CONTRIBUTORY_CAUSE        40687 non-null  object
 19  STREET_NO                      40687 non-null  float64
 20  STREET_DIRECTION               40687 non-null  object
 21  STREET_NAME                    40687 non-null  object
 22  BEAT_OF_OCCURRENCE             40687 non-null  float64
 23  NUM_UNITS                      40687 non-null  float64
 24  CRASH_MONTH                    40687 non-null  float64
 25  MOST_SEVERE_INJURY             40612 non-null  object
 26  INJURIES_TOTAL                 40612 non-null  float64
 27  INJURIES_FATAL                 40612 non-null  float64
 28  INJURIES_INCAPACITATING        40612 non-null  float64
 29  INJURIES_NON_INCAPACITATING    40612 non-null  float64
 30  INJURIES_REPORTED_NOT_EVIDENT  40612 non-null  float64
 31  INJURIES_NO_INDICATION         40612 non-null  float64
 32  INJURIES_UNKNOWN               40612 non-null  float64
 33  CRASH_HOUR                     40687 non-null  float64
 34  CRASH_DAY_OF_WEEK              40687 non-null  float64
 35  LATITUDE                       40283 non-null  float64
 36  LONGITUDE                      40283 non-null  float64
dtypes: float64(16), object(21)
memory usage: 11.8+ MB

In [14]:
df.describe()

,POSTED_SPEED_LIMIT,STREET_NO,BEAT_OF_OCCURRENCE,NUM_UNITS,CRASH_MONTH,INJURIES_TOTAL,INJURIES_FATAL,INJURIES_INCAPACITATING,INJURIES_NON_INCAPACITATING,INJURIES_REPORTED_NOT_EVIDENT,INJURIES_NO_INDICATION,INJURIES_UNKNOWN,CRASH_HOUR,CRASH_DAY_OF_WEEK,LATITUDE,LONGITUDE
count,40687.000000,40687.000000,40687.000000,40687.000000,40687.000000,40612.000000,40612.000000,40612.000000,40612.000000,40612.000000,40612.000000,40612.0,40687.000000,40687.000000,40283.000000,40283.000000
mean,28.448989,3608.076363,1272.863249,2.035441,8.615995,0.248178,0.000936,0.017876,0.129321,0.100044,1.954299,0.0,13.148131,4.115319,41.854783,-87.664729
std,5.544824,2792.070524,702.794271,0.414044,1.242807,0.644855,0.033643,0.154630,0.454657,0.418789,1.144625,0.0,5.606219,1.978693,0.558402,1.157233
min,0.000000,0.000000,111.000000,1.000000,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,1.000000,0.000000,-87.939678
25%,30.000000,1237.000000,735.000000,2.000000,8.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.0,9.000000,2.000000,41.791420,-87.721499
50%,30.000000,3143.000000,1222.000000,2.000000,9.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.0,14.000000,4.000000,41.878351,-87.674812
75%,30.000000,5424.000000,1831.000000,2.000000,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.0,17.000000,6.000000,41.928670,-87.635376
max,65.000000,13799.000000,6100.000000,14.000000,11.000000,16.000000,2.000000,4.000000,9.000000,11.000000,36.000000,0.0,23.000000,7.000000,42.022660,0.000000